version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - networkdev

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: uZD7t0J66
      MYSQL_DATABASE: inventorioistg
      # MYSQL_USER: root
      MYSQL_PASSWORD: uZD7t0J66
    networks:
      - networkdev
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3310:3310"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: uZD7t0J66
    networks:
      - networkdev
networks:
  networkdev:
    driver: bridge